# Generated by Django 5.1.5 on 2025-01-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('anger', 'Anger'), ('pride', 'Pride'), ('shame', 'Shame')], max_length=50),
        ),
    ]
